VeterinariaPatagonica/Apps/GestionDeClientes/urls.py
from django.conf.urls import url
from django.urls import path
from . import views as clientes_views
from VeterinariaPatagonica import views

app_name = 'clientes'

urlpatterns = [

    url(r'^$', clientes_views.clientes, name="cliente"),
    path('crear/', clientes_views.modificar, name="clienteCrear"),
    path('crear/<int:irAMascotas>', clientes_views.modificar, name="clienteCrear"),
    path('modificar/<int:id>/', clientes_views.modificar, name="clienteModificar"),
    path('habilitar/<int:id>/', clientes_views.habilitar, name="clienteHabilitar"),
    path('deshabilitar/<int:id>/', clientes_views.deshabilitar, name="clienteDeshabilitar"),
    path('eliminar/<int:id>/', clientes_views.eliminar, name="clienteEliminar"),
    path('ver/<int:id>/', clientes_views.ver, name="clienteVer"),
    path('verDeshabilitados/', clientes_views.verDeshabilitados, name="clienteVerDeshabilitados"),
    path('verHabilitados/', clientes_views.verHabilitados, name="clienteVerHabilitados"),
    path('listado_clientes_excel/', clientes_views.ListadoClientesExcel, name="clientesListadoEXCEL"),
    path('listado_clientes_pdf/', clientes_views.ListadoClientesPDF, name="clientesListadoPDF"),
    path('ayudaCliente/', clientes_views.ayudaContextualCliente, name="ayudaCliente"),
    path('reporteTipo/', clientes_views.reporteTipo, name='reporteTipo'),
    path('reporte/', clientes_views.reporteTopCliente, name='reporte'),
    path('reportes/', clientes_views.reportes, name='reportes'),
    #path('listado_clientes_excel/', clientes_views.exportar,{"formato" : "xlsx"} , name="clientesListadoEXCEL"),
]

VeterinariaPatagonica/Apps/GestionDeMascotas/urls.py
from django.conf.urls import url
from django.urls import path
from . import views as mascotas_views
#from VeterinariaPatagonica import views


app_name = 'mascotas'

urlpatterns = [
    url(r'^$', mascotas_views.mascota, name='mascota'),
    path('crear/', mascotas_views.modificar, name="mascotaCrear"),
    path('crear/<int:cliente_id>/', mascotas_views.modificar, name="mascotaCrearConCliente"),
    path('modificar/<int:id>/', mascotas_views.modificar, name="mascotaModificar"),
    path('habilitar/<int:id>/', mascotas_views.habilitar, name='mascotaHabilitar'),
    path('deshabilitar/<int:id>/', mascotas_views.deshabilitar, name='mascotaDeshabilitar'),
    path('eliminar/<int:id>/', mascotas_views.eliminar, name='mascotaEliminar'),
    path('ver/<int:id>/', mascotas_views.ver, name="mascotaVer"),
    path('verHabilitados/', mascotas_views.verHabilitados, name='mascotaVerHabilitados'),
    path('verDeshabilitados/', mascotas_views.verDeshabilitados, name='mascotaVerDeshabilitados'),
    path('clienteAutocomplete/', mascotas_views.clienteAutocomplete.as_view(), name='mascotaClienteAutocomplete'),
    path('listado_mascotas_excel/', mascotas_views.ListadoMascotasExcel, name="mascotasListadoExcel"),
    path('listado_mascotas_pdf/', mascotas_views.ListadoMascotasPDF, name="mascotasListadoPDF"),
    path('ayudaMascota/', mascotas_views.ayudaContextualMascota, name='ayudaMascota'),


]

VeterinariaPatagonica/VeterinariaPatagonica/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from . import views, viewsAutocomplete

app_name ="bases"
urlpatterns = [
    path("", views.index, name='index'),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("admin/", admin.site.urls),
    path('password/',include ('Apps.Usuarios.urls',namespace='usuarios')),
    path('ayuda/', views.ayuda, name='ayuda'),
    path("GestionDeClientes/", include("Apps.GestionDeClientes.urls", namespace= "clientes")),
    path("GestionDeMascotas/", include("Apps.GestionDeMascotas.urls", namespace= "mascotas")),
    path("GestionDeProductos/",include("Apps.GestionDeProductos.urls", namespace="productos")),
    path("GestionDeRubros/", include("Apps.GestionDeRubros.urls", namespace= "rubros")),
    path("GestionDeServicios/", include("Apps.GestionDeServicios.urls", namespace= "servicios")),
    path("GestionDeTiposDeAtencion/",include("Apps.GestionDeTiposDeAtencion.urls", namespace= "tiposdeatencion")),
    path("GestionDePagos/",include("Apps.GestionDePagos.urls", namespace="pagos")),
    path("GestionDeFormasDePagos/", include("Apps.GestionDeFormasDePagos.urls", namespace="formasDePagos")),
    path("GestionDeFacturas/", include("Apps.GestionDeFacturas.urls", namespace="facturas")),
    path("GestionDePracticas/", include("Apps.GestionDePracticas.urls", namespace="practicas")),

    path("autocomplete/", include(([
        path("servicio/<str:area>/", viewsAutocomplete.ServicioAutocomplete.as_view(), name="servicio"),
        path("servicio/", viewsAutocomplete.ServicioAutocomplete.as_view(), name="servicio"),
        path("insumo/", viewsAutocomplete.InsumoAutocomplete.as_view(), name="insumo"),
        path("producto/", viewsAutocomplete.ProductoAutocomplete.as_view(), name="producto"),
        path("tipoDeAtencion/", viewsAutocomplete.TipoDeAtencionAutocomplete.as_view(), name="tipoDeAtencion"),
        path("cliente/", viewsAutocomplete.ClienteAutocomplete.as_view(), name="cliente"),
        path("mascota/<int:cliente>/", viewsAutocomplete.MascotaAutocomplete.as_view(), name="mascota"),
        path("mascota/", viewsAutocomplete.MascotaAutocomplete.as_view(), name="mascota"),
        path("practicaRealizada/", viewsAutocomplete.PracticaRealizadaAutocomplete.as_view(), name="practicaRealizada"),
    ], "autocomplete")))
]

VeterinariaPatagonica/Apps/GestionDeMascotas/models.py
from datetime import datetime, date
from django.db import models
from django.core.validators import RegexValidator
from django.db.models import Q
from Apps.GestionDeClientes import models as gcmodels
from VeterinariaPatagonica.tools import BajasLogicasQuerySet

# Create your models here.
class BaseMascotaManager(models.Manager):
    def __init__(self, tipo=None):
        super().__init__()
        self.tipo = tipo

    def get_queryset(self):
        qs = super().get_queryset()
        if self.tipo is not None:
            qs = qs.filter(tipo=self.tipo)
        return qs

class MascotaQueryset(BajasLogicasQuerySet):
        MAPEO_ORDEN = {
        "orden_patente" : ["patente"],
        "orden_nombre" : ["nombre"],
        "orden_cliente" : ["cliente"],
        "orden_especie" : ["especie"],
    }

MascotaManager = BaseMascotaManager.from_queryset(MascotaQueryset)

class Mascota(models.Model):

    class Meta:
        permissions=(
            ("mascota_crear", "crear"),
            ("mascota_modificar", "modificar"),
            ("mascota_eliminar", "eliminar"),
            ("mascota_ver_habilitados", "ver_habilitados"),
            ("mascota_listar_habilitados", "listar_habilitados"),
            ("mascota_ver_no_habilitados", "ver_no_habilitados"),
            ("mascota_listar_no_habilitados", "listar_no_habilitados"),
            ('deshabilitar_mascota', 'deshabilitar_mascota')
        )
        default_permissions = ()
        ordering = ["patente"]

    MAPPER = {
        "especie": "especie__icontains",
        "cliente": "cliente",
        "patente": "patente__icontains",
        "nombre": "nombre__icontains",
        "duenio": lambda value: Q(cliente__nombres__icontains=value) | Q(cliente__apellidos__icontains=value),
        "desde": "fecha__gte"
    }

    MAXPATENTE= 6
    REGEX_NOMBRE = '^[0-9a-zA-Z-_ .]{3,100}$'
    REGEX_ESPECIE = '^[0-9a-zA-Z-_ .]{3,100}$'
    REGEX_RAZA= '^[0-9a-zA-Z-_ .]{3,100}$'
    MAX_NOMBRE = 50
    MIN_NOMBRE= 3
    MAXRAZA = 50
    MAXESPECIE =50

    patente = models.CharField( help_text= "patente la mascota",
        max_length= MAXPATENTE,
        unique= True,
        null= False,
        blank= True,
        error_messages= {
            'max_length': "la patente puede tener a lo sumo {} caracteres".format(MAXPATENTE),
            'unique': "Otra mascota tiene esa patente",
            'blank': "la patente es obligatoria"
        }
    )

    nombre = models.CharField(
        help_text= "Nombre de la mascota",
        max_length = MAX_NOMBRE,
        unique= False,
        null= False,
        blank= False,
        primary_key= False,
        validators= [RegexValidator(regex=REGEX_NOMBRE)],
        error_messages= {
            'max_length': "El nombre puede tener a lo sumo {} caracteres".format(MAX_NOMBRE),
            'blank': "El nombre es obligatorio"
        }
    )

    cliente = models.ForeignKey(
        gcmodels.Cliente,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        help_text="Ingrese cliente",
        error_messages={
        }
    )

    fechaNacimiento = models.DateField(
        help_text="Fecha de nacimiento de la mascota",
        unique=False,
        null=False,
        blank=False,
        default=datetime.now,
        error_messages={'required': "la fecha es obligatorio"})

    especie = models.CharField(
        help_text= "Especie de la Mascota",
        max_length = MAXESPECIE,
        unique= False,
        null= False,
        blank= False,
        primary_key= False,
        validators= [RegexValidator(regex=REGEX_ESPECIE)],
        error_messages= {
            'max_length': "La especie puede tener a lo sumo {} caracteres".format(MAXESPECIE),
            'blank': "La especie es obligatorio"
        }
    )

    raza = models.CharField(
        help_text="Especie de la Mascota",
        max_length=MAXRAZA,
        unique=False,
        null=False,
        blank=False,
        primary_key=False,
        validators=[RegexValidator(regex=REGEX_RAZA)],
        error_messages={
            'max_length': "La especie puede tener a lo sumo {} caracteres".format(MAXESPECIE),
            'blank': "La especie es obligatorio"}
    )


    baja = models.BooleanField(default=False)

    objects = MascotaManager()

    def __str__(self):
        return "{0}, {1}".format(self.nombre, self.especie)


    def generadorDePatente(self, id):

         if self.patente is '':
             self.patente= "Vet-" + str(id)
         return self.patente

VeterinariaPatagonica/VeterinariaPatagonica/Apps/GestionDeMascotas/models.py
from django.db import models

from VeterinariaPatagonica.Apps.GestionDeClientes.models import *

# Create your models here.

class Mascota(models.Model):
    patente = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=35)
    cliente = models.ForeignKey(Cliente, null=False, blank=False, on_delete=models.CASCADE)
    fechaNacimiento = models.DateTimeField()
    especie = models.CharField(max_length=40)
    raza = models.CharField(max_length=40)

    def __str__ (self):
        return "{0}, {1}, {2}".format(self.nombre,self.especie,self.raza)

VeterinariaPatagonica/Apps/GestionDeMascotas/forms.py
from django import forms
from .models import Mascota
from dal import autocomplete


cliente = forms.DateField(
    required=True,
    label='cliente',
    widget=forms.CharField,
    help_text='Cliente',
    error_messages={
        'invalid_choice': "La opcion no es valida",
        'required': "el cliente es obligatorio"
    },
    validators=[],

)
def MascotaFormFactory(mascota=None, cliente=None):
    campos = [ 'nombre', 'cliente',
               'fechaNacimiento',
               'especie', 'raza' ]

    if mascota is None:
        campos.insert(0, 'patente')



    class MascotaForm(forms.ModelForm):

        class Meta:
            model = Mascota
            fields = campos
            widget_cliente = autocomplete.ModelSelect2(url='/GestionDeMascotas/clienteAutocomplete')
            if cliente:
                #widget_cliente = forms.TextInput(attrs={'value': cliente})
                widget_cliente = autocomplete.ModelSelect2(url='/GestionDeMascotas/clienteAutocomplete/?q={}'.format(cliente.dniCuit))

            labels = {
                'patente':'Patente:',
                'cliente': "Cliente:",
                'fechaNacimiento': 'Fecha de Nacimiento:',
                'nombre':'Nombre:',
                'especie':'Especie:',
                'raza': 'Raza:',
                'baja':'Baja:'
            }
            error_messages = {
                'nombre' : {
                    'max_length': ("Nombre demasiados largos"),
                },
                'patente' : {
                    'max_length' : ("patente demasiado largo"),
                    'unique' : ("Esa patente ya existe"),
                }
            }
            widgets = {
                'nombre' : forms.TextInput(),
                'cliente': widget_cliente,
                #'cliente': forms.Select(attrs={'class': 'form-control'}),
                'fechaNacimiento': forms.DateInput(),
                'raza' : forms.TextInput(),
                'especie': forms.TextInput(),
            }

        def clean(self):
            cleaned_data = super().clean()
            return cleaned_data

        def __init__(self, *args, **kwargs):

            super().__init__(*args, **kwargs)

            # [TODO] Averiguar una mejor manera de hacer esto:
            for field in self.fields.values():
                if not isinstance(field.widget, forms.CheckboxInput):
                    field.widget.attrs.update({
                        'class': 'form-control'
                    })

    return MascotaForm

class FiltradoForm(forms.Form):

    ordenes = (
        ("d", "Descendente"),
        ("a", "Ascendente"),
    )

    criterios = (
        ("patente", "Patente"),
        ("nombre", "Nombre"),
        ("cliente", "Dueño"),
        ("especie", "Especie"),
    )

    patente = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            "placeholder":"Patente...",
            "class":"form-control"
        })
    )

    nombre = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            "placeholder":"Nombre...",
            "class":"form-control"
        })
    )

    cliente = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            "placeholder":"Dueño...",
            "class":"form-control"
        })
    )

    especie = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            "placeholder":"Especie...",
            "class":"form-control",
        })
    )

    def filtros(self):
        retorno = {}
        if self.is_valid():
            fields = ("patente", "nombre", "cliente", "especie")
            for field in fields:
                if field in self.cleaned_data and self.cleaned_data[field]:
                    retorno[field] = self.cleaned_data[field]
        return retorno

    def criterio(self):
        if self.cleaned_data and "segun" in self.cleaned_data:
            return self.cleaned_data["segun"]
        return None

    def ascendente(self):
        if self.cleaned_data and "orden" in self.cleaned_data:
            return (self.cleaned_data["orden"] == "a")
        return None

VeterinariaPatagonica/Apps/GestionDeMascotas/templates/GestionDeMascotas/GestionDeMascotas.html
{% extends "sitioBase.html" %}
{% load static %}

{% block paginaSeccionGeneral %}
  <section>

      {% block secciones %}
      {% endblock %}

      <div class="row">
        <div class="col-xs-10 col-sm-11 col-md-11">
          <h4 class="titulo">
            {% block tituloSeccion %}
            {% endblock %}
          </h4>
        </div>
        <div class="col-xs-2 col-sm-1 col-md-1">
          <a href="{% url 'mascotas:ayudaMascota' %}" target="_blank">
            <i class="glyphicon glyphicon-book"></i>
          </a>
        </div>
      </div>

      {% block contenido %}
      {% endblock contenido %}
      
  </section>
{% endblock paginaSeccionGeneral %}


{% block footer %}
  <p>Para mas información  de los Mascotas haga click aquí<p>
{% endblock footer %}

{% block paginaJavascript %}
    {{block.super}}
    <script src="{% static 'js/GestionDeMascotas.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/es.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js'%}"></script>
{% endblock paginaJavascript %}

VeterinariaPatagonica/Apps/GestionDeMascotas/templates/GestionDeMascotas/accionesSnippet.html
<div class="mascotaItemAcciones">

        {% if seccion != 'ver' %}
        <a  class="btn btn-sm btn-default" href="{% url 'mascotas:mascotaVer' item.id %}">Ver</a>
        {% endif %}

        {% if seccion != 'modificar' %}
        <a  class="btn btn-sm btn-default" href="{% url 'mascotas:mascotaModificar' item.id %}">Modificar</a>
        {% endif %}

        {% if item.baja == False %}
            <a  class="btn btn-sm btn-default" href="{% url 'mascotas:mascotaDeshabilitar' item.id %}">Deshabilitar</a>
        {% else %}
            <a  class="btn btn-sm btn-default" href="{% url 'mascotas:mascotaHabilitar' item.id %}">Habilitar</a>
        {% endif %}

</div>

VeterinariaPatagonica/Apps/GestionDeMascotas/templates/GestionDeMascotas/eliminar.html
{% extends 'GestionDeMascotas/GestionDeMascotas.html' %}

{% block titulo %}
Gestion de Mascotas| Eliminar Mascota
{% endblock %}

{% block mascotaTitulo %}
Eliminar Mascota
{% endblock %}

{% block mascotaSubtitulo %}
Elimina permanentemente los datos de la mascota del sistema
{% endblock %}

{% block mascotaContenido %}
<div class="mascotaCuerpo">
    <form class="form" action="{% url 'mascotas:mascotaEliminar' id %}" method="post">
        {% csrf_token %}
		<p class="mascotaAvisoEliminacion"> Confirmar eliminacion: </p>
        <button type="submit" class="btn btn-sm btn-default center-block">Eliminar</button>
    </form>
</div>
{% endblock mascotaContenido %}

VeterinariaPatagonica/Apps/GestionDeMascotas/templates/GestionDeMascotas/formulario.html
{% extends 'GestionDeMascotas/GestionDeMascotas.html' %}
{% load static %}

{% block paginaEstilos %}
    {{ block.super }}
    <link href="{% static "vendor/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" %}" rel="stylesheet">
    <link href="{% static "css/tema-datetimepicker.css" %}" rel="stylesheet">
{% endblock %}

{% block titulo %}
Gestion de Mascotas | {{titulo}}
{% endblock %}

{% block tituloSeccion %}
{% if titulo == 1 %}
    {% include "snippets/titulo.html" with titulo="Nueva Mascota" %}
{% endif %}
{% if titulo == 2 %}
    {% include "snippets/titulo.html" with titulo="Modificar Mascota" %}
{% endif %}
{% endblock %}

{% block contenido %}
{{form.media}}

    <form class="form-horizontal formulario" action="{{ request.path }}" method="post">

        {% csrf_token %}

        {% if form.errors %}
            <div class="errores">
                <strong>Por favor revise los siguientes errores:</strong>
                <ul>
                    {% include "snippets/formErrores.html" %}
                </ul>
            </div>
        {% endif %}

        {% include "./snippets/form.html" with accion="Guardar Datos" %}


    </form>

{% endblock %}

{% block paginaJavascript %}
    {{block.super}}
    <script src="{% static "vendor/moment/moment.js" %}"></script>
    <script src="{% static "vendor/moment/locale/es.js" %}"></script>
    <script src="{% static "vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script src="{% static 'js/GestionDeMascotas.js' %}"></script>
    <script type="text/javascript">
    $(function () {
            var today = new Date();
            var date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
            var time = today.getHours() + ":" + today.getMinutes();
            var dateTime = date+' '+time;
            $("#id_fechaNacimiento").datetimepicker({
                locale: 'es',
                format: 'L',
                maxDate: new Date()
            });

    });

    </script>
{% endblock %}

VeterinariaPatagonica/Apps/GestionDeMascotas/templates/GestionDeMascotas/seccionesSnippet.html
<div class="mascotaSecciones">

        <a id="mascotaLinkHabilitados" class="btn btn-sm btn-default {% if pagina == 'verHabilitados' %} disabled {% endif %}"  href="{% url 'mascotas:mascotaVerHabilitados' %}"> Habilitados </a>

        <a id="mascotalinkDeshabilitados" class="btn btn-sm btn-default {% if pagina == 'verDeshabilitados' %} disabled {% endif %}"  href="{% url 'mascotas:mascotaVerDeshabilitados' %}"> Deshabilitados </a>

</div>

VeterinariaPatagonica/Apps/GestionDeMascotas/templates/GestionDeMascotas/ver.html
{% extends 'GestionDeMascotas/GestionDeMascotas.html' %}

{% block titulo %}
Gestion de Mascotas | Ver Mascota
{% endblock %}

{% block tituloSeccion %}
{% include "snippets/titulo.html" with titulo="Mascota: "|add:mascota.patente %}
{% endblock %}

{% block contenido %}

    <div>
        <p> <strong>Patente: </strong>{{mascota.patente}} 
        <p> <strong>Dueño: </strong>{{mascota.cliente}}</p>
        <p> <strong>Nombre:</strong> {{ mascota.nombre }} ({% if mascota.baja %}Deshabilitado{% else %}Habilitado{% endif %})</p>
        <p> <strong>Especie:</strong> {{mascota.especie}} </p>
        <p> <strong>Fecha de Nacimiento: </strong>{{ mascota.fechaNacimiento}}</p>
        <p> <strong>Raza: </strong>{{ mascota.raza}}</p>
    </div>

    <div class= "col-sm-offset-11">
      <a><span class="glyphicon glyphicon-arrow-left" type=button onClick="javascript:history.go(-1);" data-toggle="tooltip" data-placement="bottom" title="Volver atrás."></a>
    </div>

{% endblock contenido %}