VeterinariaPatagonica/Apps/GestionDeClientes/urls.py
from django.conf.urls import url
from django.urls import path
from . import views as clientes_views
from VeterinariaPatagonica import views

app_name = 'clientes'

urlpatterns = [

    url(r'^$', clientes_views.clientes, name="cliente"),
    path('crear/', clientes_views.modificar, name="clienteCrear"),
    path('crear/<int:irAMascotas>', clientes_views.modificar, name="clienteCrear"),
    path('modificar/<int:id>/', clientes_views.modificar, name="clienteModificar"),
    path('habilitar/<int:id>/', clientes_views.habilitar, name="clienteHabilitar"),
    path('deshabilitar/<int:id>/', clientes_views.deshabilitar, name="clienteDeshabilitar"),
    path('eliminar/<int:id>/', clientes_views.eliminar, name="clienteEliminar"),
    path('ver/<int:id>/', clientes_views.ver, name="clienteVer"),
    path('verDeshabilitados/', clientes_views.verDeshabilitados, name="clienteVerDeshabilitados"),
    path('verHabilitados/', clientes_views.verHabilitados, name="clienteVerHabilitados"),
    path('listado_clientes_excel/', clientes_views.ListadoClientesExcel, name="clientesListadoEXCEL"),
    path('listado_clientes_pdf/', clientes_views.ListadoClientesPDF, name="clientesListadoPDF"),
    path('ayudaCliente/', clientes_views.ayudaContextualCliente, name="ayudaCliente"),
    path('reporteTipo/', clientes_views.reporteTipo, name='reporteTipo'),
    path('reporte/', clientes_views.reporteTopCliente, name='reporte'),
    path('reportes/', clientes_views.reportes, name='reportes'),
    #path('listado_clientes_excel/', clientes_views.exportar,{"formato" : "xlsx"} , name="clientesListadoEXCEL"),
]

VeterinariaPatagonica/Apps/GestionDeFacturas/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'facturas'


urlpatterns = [
    path('facturar/practica/<int:id>/', views.facturarPractica, name='facturarPractica'),
    path('facturar/', views.facturar, name='facturar'),
    path("listar/", views.listar, name="listar"),
    path("ver/<int:id>/", views.ver, name="ver"),
    path("exportar/", include(([
        path("xlsx/", views.exportar, {"formato" : "xlsx"}, name="xlsx"),
    ], "exportar"))),
    path('ayudaCostos/', views.ayudaContextualCosto, name="ayudaCostos"),
]

VeterinariaPatagonica/Apps/GestionDeMascotas/urls.py
from django.conf.urls import url
from django.urls import path
from . import views as mascotas_views
#from VeterinariaPatagonica import views


app_name = 'mascotas'

urlpatterns = [
    url(r'^$', mascotas_views.mascota, name='mascota'),
    path('crear/', mascotas_views.modificar, name="mascotaCrear"),
    path('crear/<int:cliente_id>/', mascotas_views.modificar, name="mascotaCrearConCliente"),
    path('modificar/<int:id>/', mascotas_views.modificar, name="mascotaModificar"),
    path('habilitar/<int:id>/', mascotas_views.habilitar, name='mascotaHabilitar'),
    path('deshabilitar/<int:id>/', mascotas_views.deshabilitar, name='mascotaDeshabilitar'),
    path('eliminar/<int:id>/', mascotas_views.eliminar, name='mascotaEliminar'),
    path('ver/<int:id>/', mascotas_views.ver, name="mascotaVer"),
    path('verHabilitados/', mascotas_views.verHabilitados, name='mascotaVerHabilitados'),
    path('verDeshabilitados/', mascotas_views.verDeshabilitados, name='mascotaVerDeshabilitados'),
    path('clienteAutocomplete/', mascotas_views.clienteAutocomplete.as_view(), name='mascotaClienteAutocomplete'),
    path('listado_mascotas_excel/', mascotas_views.ListadoMascotasExcel, name="mascotasListadoExcel"),
    path('listado_mascotas_pdf/', mascotas_views.ListadoMascotasPDF, name="mascotasListadoPDF"),
    path('ayudaMascota/', mascotas_views.ayudaContextualMascota, name='ayudaMascota'),


]

VeterinariaPatagonica/Apps/GestionDePagos/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


app_name = 'pagos'


urlpatterns = [
    path('crear/<int:id>/', views.crear, name="crear"),
    path('listar/', views.listar, name="listar"),
    path('ver/<int:id>/', views.ver, name="ver"),
]

VeterinariaPatagonica/Apps/Usuarios/urls.py
from django.conf.urls import url
from . import views

app_name = 'usuarios'
urlpatterns = [
    url(r'^changePassword/$', views.changePassword, name='changePassword'),
]

VeterinariaPatagonica/VeterinariaPatagonica/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from . import views, viewsAutocomplete

app_name ="bases"
urlpatterns = [
    path("", views.index, name='index'),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("admin/", admin.site.urls),
    path('password/',include ('Apps.Usuarios.urls',namespace='usuarios')),
    path('ayuda/', views.ayuda, name='ayuda'),
    path("GestionDeClientes/", include("Apps.GestionDeClientes.urls", namespace= "clientes")),
    path("GestionDeMascotas/", include("Apps.GestionDeMascotas.urls", namespace= "mascotas")),
    path("GestionDeProductos/",include("Apps.GestionDeProductos.urls", namespace="productos")),
    path("GestionDeRubros/", include("Apps.GestionDeRubros.urls", namespace= "rubros")),
    path("GestionDeServicios/", include("Apps.GestionDeServicios.urls", namespace= "servicios")),
    path("GestionDeTiposDeAtencion/",include("Apps.GestionDeTiposDeAtencion.urls", namespace= "tiposdeatencion")),
    path("GestionDePagos/",include("Apps.GestionDePagos.urls", namespace="pagos")),
    path("GestionDeFormasDePagos/", include("Apps.GestionDeFormasDePagos.urls", namespace="formasDePagos")),
    path("GestionDeFacturas/", include("Apps.GestionDeFacturas.urls", namespace="facturas")),
    path("GestionDePracticas/", include("Apps.GestionDePracticas.urls", namespace="practicas")),

    path("autocomplete/", include(([
        path("servicio/<str:area>/", viewsAutocomplete.ServicioAutocomplete.as_view(), name="servicio"),
        path("servicio/", viewsAutocomplete.ServicioAutocomplete.as_view(), name="servicio"),
        path("insumo/", viewsAutocomplete.InsumoAutocomplete.as_view(), name="insumo"),
        path("producto/", viewsAutocomplete.ProductoAutocomplete.as_view(), name="producto"),
        path("tipoDeAtencion/", viewsAutocomplete.TipoDeAtencionAutocomplete.as_view(), name="tipoDeAtencion"),
        path("cliente/", viewsAutocomplete.ClienteAutocomplete.as_view(), name="cliente"),
        path("mascota/<int:cliente>/", viewsAutocomplete.MascotaAutocomplete.as_view(), name="mascota"),
        path("mascota/", viewsAutocomplete.MascotaAutocomplete.as_view(), name="mascota"),
        path("practicaRealizada/", viewsAutocomplete.PracticaRealizadaAutocomplete.as_view(), name="practicaRealizada"),
    ], "autocomplete")))
]

VeterinariaPatagonica/templates/error.html
{% extends "sitioBase.html" %}
{% block paginaSeccionGeneral %}
<section>
    <div class="contenedor">
        <div class="errores">
            {% for excepcion in excepciones %}
                {% include "snippets/excepcion.html" %}
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

VeterinariaPatagonica/templates/menu-dch_snippet.html
      <table class="table tabla-menu-dch">
          <thead>
              <tr> <th class="menu-subtitulo"><span>Acciones</span><span class="glyphicon glyphicon-chevron-up icono-thead"></span></th> </tr>
          </thead>
          <tbody>
            <tr> <td><a href="{% url 'logout' %}">Cerrar Sesion</a></td> </tr>
            <tr> <td><a href="#">Link</a></td> </tr>
            <tr> <td><a href="#">Link</a></td> </tr>
            <tr> <td><a href="#">Link</a></td> </tr>
          </tbody>
      </table>

      <table class="table tabla-menu-dch">
          <thead>
              <tr> <th class="menu-subtitulo"><span>Relacionados</span><span class="glyphicon glyphicon-chevron-up icono-thead"></span></th> </tr>
          </thead>
          <tbody>
            <tr> <td><a href="#">Funcionalidad</a></td> </tr>
            <tr> <td><a href="#">Funcionalidad</a></td> </tr>
          </tbody>
      </table>

VeterinariaPatagonica/templates/sitioBase.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="/../static/images/iconoBarraNavegacion.jpg">
{% block paginaEstilos %}
  <link href="{% static 'vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/fontawesome/css/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'css/veterinaria-patagonica.css' %}" rel="stylesheet">
{% endblock paginaEstilos %}
  <title>
{% block paginaTitulo %}
  Veterinaria Patagónica
{% endblock paginaTitulo %}
  </title>
  </head>
  <body>
  <div class="container-fluid" id="el_container_fluid">
  {% block cabecera %}
  <div class="row">
    <header class="col-xs-12" id="sitio-encabezado">
      <h2><a href="{% url "index" %}">Veterinaria Patagónica</a></h2>
    </header>
    <nav id="sitio-navbar" class="col-xs-12 navbar">
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown menu-usuario">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
            Menu de usuario <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
          {% block menuUsuario %}
            <li>
              <div class="usuario">
                <i class="fa fa-user"></i>
                <b>{{ request.user.username|lower }}</b>
              </div>
            </li>
            {% block menuAyuda %}
            <li><a href="{% url "ayuda"%}" target="_blank"><i class="glyphicon glyphicon-book"></i>Manual de usuario</a></li>
            {% endblock %}
            {% if not request.user.esAdministrativo %}
            <li>
              <a href="{% url "practicas:realizaciones" %}">
                <i class="fa fa-history"></i>
                Prácticas realizadas
              </a>
            </li>
            {% endif %}
            <li>
              <a href="{% url 'usuarios:changePassword' %}">
                <i class="glyphicon glyphicon-edit "></i>
                Cambiar contraseña
              </a>
            </li>
            <li>
              <a href="{% url "logout" %}">
                <i class="fa fa-sign-out "></i>
                Cerrar Sesión</a>
              </li>
          {% endblock %}
          </ul>
        </li>
      </ul>
    </nav>
  </div>
  {% endblock cabecera %}
  <div class="row" id="fila_centro" >
    <nav class="col-xs-12 col-sm-4 col-md-3 navbar sitio-menu" id="sitio_menu_izq">
      <div class="left_col scroll-view">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-menu">
            <i class="fa fa-navicon"> </i>
          </button>
        </div>
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu collapse navbar-collapse">
          {% block paginaMenuIzq %}
          {% if request.user.esGerente %}
            {% include './menu/gerentes.html' %}
          {% elif request.user.esVeterinario %}
            {% include './menu/veterinarios.html' %}
          {% elif request.user.esAdministrativo %}
            {% include './menu/administrativos.html' %}
          {% endif %}
          {% endblock paginaMenuIzq %}
        </div>
      </div>
    </nav>
    <div class="col-xs-12 col-sm-8 col-md-9" id="sitio_seccion_principal">
      <div class="contenedor">
        {% block paginaSeccionGeneral %}
          <section>
            <div class="col-xs-6 col-sm-4 col-md-3" >
              <a class="btn btn-primary cuadradito" href="{% url "clientes:clienteCrear" %}" role="button" id="imagenCliente"></a>
              <p class= "text-primary">Crear un Cliente</p>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3">
              <a class="btn btn-primary cuadradito" href="{% url "mascotas:mascotaCrear" %}" role="button" id="imagenMascota"></a>
              <p class= "text-primary">Crear una Mascota</p>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3">
              <a class="btn btn-primary cuadradito" href="{% url "productos:productoCrear" %}" role="button" id="imagenProducto"></a>
              <p class= "text-primary">Crear un Producto / Insumo</p>
            </div>
            <div class="col-xs-6 col-sm-4 col-md-3">
            <a class="btn btn-primary cuadradito" href="{% url "practicas:consulta:crear:practica" %}" role="button" id="imagenConsulta"></a>
            <p class= "text-primary">Crear una Consulta</p>
            </div>
            {% if request.user.esGerente %}
            <div class="col-xs-6 col-sm-4 col-md-3">
              <a class="btn btn-primary cuadradito" href="{% url "servicios:servicioCrear" %}" role="button" id="imagenServicio"></a>
              <p class= "text-primary">Crear un Servicio</p>
            </div>
            {% endif %}
            {% if request.user.esGerente or request.user.esAdministrativo%}
            <div class="col-xs-6 col-sm-4 col-md-3">
              <a class="btn btn-primary cuadradito" href="{% url "facturas:facturar" %}" role="button" id="imagenFactura"></a>
              <p class= "text-primary">Crear una Factura</p>
            </div>
            {% endif %}
            {% if request.user.esGerente %}
            <div class="col-xs-6 col-sm-4 col-md-3">
              <a class="btn btn-primary cuadradito" href="{% url "tiposdeatencion:crear" %}" role="button" id="imagenTipoDeAtencion"></a>
              <p class= "text-primary">Crear un Tipo de Atención</p>
            </div>
            {% endif %}
            <div class="col-xs-6 col-sm-4 col-md-3">
              <a class="btn btn-primary cuadradito" href="{% url "practicas:cirugia:crear:practica" %}" role="button" id="imagenCirugia"></a>
              <p class= "text-primary">Crear una Cirugía</p>
            </div>
          </section>
        {% endblock paginaSeccionGeneral %}
      </div>
    </div>
    </div>
    <div class="row">
      <footer class="col-xs-12" id="sitio-piedepagina">
        {% block paginaPie %}
          <p>Último inicio de sesión registrado el {{ request.user.last_login|date:"d/m/y" }} a las {{ request.user.last_login|date:"H:i" }}</p>
        {% endblock paginaPie %}
      </footer>
    </div>
  </div>
  {% block paginaJavascript %}
    <script src="{% static 'vendor/jquery/js/jquery.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'js/veterinaria-patagonica.js' %}"></script>
  {% endblock paginaJavascript %}
  </body>
</html>

VeterinariaPatagonica/templates/sitio_base2.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
      <title>Veterinaria Patagonica</title>
      <!-- Bootstrap -->
      <link href="{% static 'gentelella/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Font Awesome -->
      <link href="{% static 'gentelella/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
      <!-- NProgress -->
      <link href="{% static 'gentelella/nprogress/nprogress.css' %}" rel="stylesheet">
      <!-- iCheck -->
      <link href="{% static 'gentelella/iCheck/skins/flat/green.css' %}" rel="stylesheet">
      <!-- bootstrap-progressbar -->
      <link href="{% static 'gentelella/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
      <!-- JQVMap -->
      <link href="{% static 'gentelella/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
      <!-- bootstrap-daterangepicker -->
      <link href="{% static 'gentelella/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
      <!-- Custom Theme Style -->
      <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  </head>
  {% block body %}
  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    <div class="container-fluid">
      <div class="row" >
        <header>
          <h1>Veterinaria</h1>
          <!--Button Base-->
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
          </nav>
          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                Menu De Usuario
                <span class=" fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li><a href="javascript:;">Ayuda</a></li>
                <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Cerrar Sesión</a></li>
              </ul>
            </li>
          </ul>
        </header>
      </div>
    	<nav class="col-md-3 left_col">
    		<div class="left_col scroll-view">
    			<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    				<div class="menu_section">
    					<h3>Menu General</h3>
    					<ul class="nav side-menu">
                <li><a href="#"><i class="fa fa-angle-right"></i> Clientes </a>
    							<ul class="nav child_menu">
    								<li><a href="{% url 'clientes:cliente' %}">Inicio</a></li>
    								<li><a href="{% url 'clientes:alta' %}">Alta</a></li>
    								<li><a href="#">Baja</a></li>
    								<li><a href="#">Modificacion</a></li>
    							</ul>
    						</li>
                <li><a href="#"><i class="fa fa-angle-right"></i> Insumos </a>
    							<ul class="nav child_menu">
    								<li><a href="{% url 'insumos:insumo' %}">Inicio</a></li>
    								<li><a href="{% url 'insumos:alta' %}">Alta</a></li>
    								<li><a href="#">Baja</a></li>
    								<li><a href="#">Modificacion</a></li>
    							</ul>
    						</li>
                <li><a href="#"><i class="fa fa-angle-right"></i> Servicios </a>
    							<ul class="nav child_menu">
    								<li><a href="{% url 'servicios:servicio' %}">Inicio</a></li>
    								<li><a href="{% url 'servicios:alta' %}">Alta</a></li>
    								<li><a href="#">Baja</a></li>
    								<li><a href="#">Modificacion</a></li>
    							</ul>
    						</li>
                <li><a href="#"><i class="fa fa-angle-right"></i> Mascotas </a>
    							<ul class="nav child_menu">
    								<li><a href="{% url 'mascotas:mascota' %}">Inicio</a></li>
    								<li><a href="{% url 'mascotas:alta' %}">Alta</a></li>
    								<li><a href="#">Baja</a></li>
    								<li><a href="#">Modificacion</a></li>
    							</ul>
    						</li>
    					</ul>
    				</div>
    			</div>
    			<div class="sidebar-footer hidden-small">
    				<a data-toggle="tooltip" data-placement="top" title="Settings">
    					<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    				</a>
    				<a data-toggle="tooltip" data-placement="top" title="FullScreen">
    					<span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    				</a>
    				<a data-toggle="tooltip" data-placement="top" title="Lock">
    					<span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    				</a>
    				<a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
    					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    				</a>
    			</div>
    		</div>
    	</nav>
        <section class="col-md-7 middle_col">
          <a class="btn btn-primary" href="{% url "clientes:alta" %}" role="button" style="height : 100px; width : 100px; display:table-cell;vertical-align:center; background-color: blue;">Clientes</a>
          <a class="btn btn-primary" href="{% url "insumos:alta" %}" role="button" style="height : 100px; width : 100px; display:table-cell;vertical-align:center; background-color: red;">Insumos</a>
          <a class="btn btn-primary" href="{% url "servicios:alta" %}" role="button" style="height : 100px; width : 100px; display:table-cell;vertical-align:center; background-color: silver;">Servicios</a>
          <a class="btn btn-primary" href="{% url "mascotas:alta" %}" role="button" style="height : 100px; width : 100px; display:table-cell;vertical-align:center; background-color: orange;">Mascotas</a>
          {% block content %}
          <h1>Dashboard Principal
          </h1>
          {% endblock %}
          <footer>{% block footer %}
            <p>Pie de Pagina Principal.
            </p>
          </footer>
          {% endblock %}
        </section>
        <nav class="col-md-2 right_col">
  		      nav2
  	    </nav>
    </div>
    {% endblock body %}
    <!--<script src="{% static 'jquery/jquery-3.3.1.min.js'%}" type="text/javascript"></script>-->
    <script src="{% static 'popper/popper.min.js'%}" type="text/javascript"></script>
    <!--<script src="{% static 'bootstrap/js/bootstrap.js'%}" type="text/javascript"></script>-->
    {% block javascripts %}
      <!-- jQuery -->
      <script src="{% static 'gentelella/jquery/dist/jquery.min.js' %}"></script>
      <!-- Bootstrap -->
      <script src="{% static 'gentelella/bootstrap/dist/js/bootstrap.min.js' %}"></script>
      <!-- FastClick -->
      <script src="{% static 'gentelella/fastclick/lib/fastclick.js' %}"></script>
      <!-- NProgress -->
      <script src="{% static 'gentelella/nprogress/nprogress.js' %}"></script>
      <!-- Chart.js -->
      <script src="{% static 'gentelella/Chart.js/dist/Chart.min.js' %}"></script>
      <!-- gauge.js -->
      <script src="{% static 'gentelella/gauge.js/dist/gauge.min.js' %}"></script>
      <!-- bootstrap-progressbar -->
      <script src="{% static 'gentelella/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
      <!-- iCheck -->
      <script src="{% static 'gentelella/iCheck/icheck.min.js' %}"></script>
      <!-- Skycons -->
      <script src="{% static 'gentelella/skycons/skycons.js' %}"></script>
      <!-- Flot -->
      <script src="{% static 'gentelella/Flot/jquery.flot.js' %}"></script>
      <script src="{% static 'gentelella/Flot/jquery.flot.pie.js' %}"></script>
      <script src="{% static 'gentelella/Flot/jquery.flot.time.js' %}"></script>
      <script src="{% static 'gentelella/Flot/jquery.flot.stack.js' %}"></script>
      <script src="{% static 'gentelella/Flot/jquery.flot.resize.js' %}"></script>
      <!-- Flot plugins -->
      <script src="{% static 'gentelella/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
      <script src="{% static 'gentelella/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
      <script src="{% static 'gentelella/flot.curvedlines/curvedLines.js' %}"></script>
      <!-- DateJS -->
      <script src="{% static 'gentelella/DateJS/build/date.js' %}"></script>
      <!-- JQVMap -->
      <script src="{% static 'gentelella/jqvmap/dist/jquery.vmap.js' %}"></script>
      <script src="{% static 'gentelella/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
      <script src="{% static 'gentelella/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
      <!-- bootstrap-daterangepicker -->
      <script src="{% static 'gentelella/moment/min/moment.min.js' %}"></script>
      <script src="{% static 'gentelella/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
      <!-- Custom Theme Scripts -->
      <script src="{% static 'js/custom.min.js' %}"></script>
    {% endblock %}
  </body>
</html>