VeterinariaPatagonica/Apps/GestionDeClientes/urls.py
from django.conf.urls import url
from django.urls import path
from . import views as clientes_views
from VeterinariaPatagonica import views

app_name = 'clientes'

urlpatterns = [

    url(r'^$', clientes_views.clientes, name="cliente"),
    path('crear/', clientes_views.modificar, name="clienteCrear"),
    path('crear/<int:irAMascotas>', clientes_views.modificar, name="clienteCrear"),
    path('modificar/<int:id>/', clientes_views.modificar, name="clienteModificar"),
    path('habilitar/<int:id>/', clientes_views.habilitar, name="clienteHabilitar"),
    path('deshabilitar/<int:id>/', clientes_views.deshabilitar, name="clienteDeshabilitar"),
    path('eliminar/<int:id>/', clientes_views.eliminar, name="clienteEliminar"),
    path('ver/<int:id>/', clientes_views.ver, name="clienteVer"),
    path('verDeshabilitados/', clientes_views.verDeshabilitados, name="clienteVerDeshabilitados"),
    path('verHabilitados/', clientes_views.verHabilitados, name="clienteVerHabilitados"),
    path('listado_clientes_excel/', clientes_views.ListadoClientesExcel, name="clientesListadoEXCEL"),
    path('listado_clientes_pdf/', clientes_views.ListadoClientesPDF, name="clientesListadoPDF"),
    path('ayudaCliente/', clientes_views.ayudaContextualCliente, name="ayudaCliente"),
    path('reporteTipo/', clientes_views.reporteTipo, name='reporteTipo'),
    path('reporte/', clientes_views.reporteTopCliente, name='reporte'),
    path('reportes/', clientes_views.reportes, name='reportes'),
    #path('listado_clientes_excel/', clientes_views.exportar,{"formato" : "xlsx"} , name="clientesListadoEXCEL"),
]

VeterinariaPatagonica/Apps/GestionDeFacturas/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views


app_name = 'facturas'


urlpatterns = [
    path('facturar/practica/<int:id>/', views.facturarPractica, name='facturarPractica'),
    path('facturar/', views.facturar, name='facturar'),
    path("listar/", views.listar, name="listar"),
    path("ver/<int:id>/", views.ver, name="ver"),
    path("exportar/", include(([
        path("xlsx/", views.exportar, {"formato" : "xlsx"}, name="xlsx"),
    ], "exportar"))),
    path('ayudaCostos/', views.ayudaContextualCosto, name="ayudaCostos"),
]

VeterinariaPatagonica/Apps/GestionDeProductos/urls.py
from django.conf.urls import url
from django.urls import path
from . import views as productos_views 

app_name = 'productos'

urlpatterns = [
    url(r'^$', productos_views.producto, name='producto'),
    path('crear/', productos_views.modificar, name='productoCrear'),
    path('modificar/<int:id>/', productos_views.modificar, name='productoModificar'),
    path('habilitar/<int:id>/', productos_views.habilitar, name='productoHabilitar'),
    path('deshabilitar/<int:id>/', productos_views.deshabilitar, name='productoDeshabilitar'),
    path('eliminar/<int:id>/', productos_views.eliminar, name='productoEliminar'),
    path('ver/<int:id>/', productos_views.ver, name='productoVer'),
    path('verHabilitados/', productos_views.verHabilitados, name='productoVerHabilitados'),
    path('verDeshabilitados/', productos_views.verDeshabilitados, name='productoVerDeshabilitados'),
    path('rubroAutocomplete/', productos_views.rubroAutocomplete.as_view(), name='productoRubroAutocomplete'),
    path('listado_productos_excel/', productos_views.ListadoProductosExcel, name="productosListadoExcel"),
    path('listado_productos_pdf/', productos_views.ListadoProductosPDF, name="productosListadoPDF"),
    path('ayudaProducto/', productos_views.ayudaContextualProducto, name='ayudaProducto'),
    path('reporte_productos_vendidos/', productos_views.reporteProductosVendidos, name = 'reporteProductosVendidos'),
]

VeterinariaPatagonica/VeterinariaPatagonica/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from . import views, viewsAutocomplete

app_name ="bases"
urlpatterns = [
    path("", views.index, name='index'),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("admin/", admin.site.urls),
    path('password/',include ('Apps.Usuarios.urls',namespace='usuarios')),
    path('ayuda/', views.ayuda, name='ayuda'),
    path("GestionDeClientes/", include("Apps.GestionDeClientes.urls", namespace= "clientes")),
    path("GestionDeMascotas/", include("Apps.GestionDeMascotas.urls", namespace= "mascotas")),
    path("GestionDeProductos/",include("Apps.GestionDeProductos.urls", namespace="productos")),
    path("GestionDeRubros/", include("Apps.GestionDeRubros.urls", namespace= "rubros")),
    path("GestionDeServicios/", include("Apps.GestionDeServicios.urls", namespace= "servicios")),
    path("GestionDeTiposDeAtencion/",include("Apps.GestionDeTiposDeAtencion.urls", namespace= "tiposdeatencion")),
    path("GestionDePagos/",include("Apps.GestionDePagos.urls", namespace="pagos")),
    path("GestionDeFormasDePagos/", include("Apps.GestionDeFormasDePagos.urls", namespace="formasDePagos")),
    path("GestionDeFacturas/", include("Apps.GestionDeFacturas.urls", namespace="facturas")),
    path("GestionDePracticas/", include("Apps.GestionDePracticas.urls", namespace="practicas")),

    path("autocomplete/", include(([
        path("servicio/<str:area>/", viewsAutocomplete.ServicioAutocomplete.as_view(), name="servicio"),
        path("servicio/", viewsAutocomplete.ServicioAutocomplete.as_view(), name="servicio"),
        path("insumo/", viewsAutocomplete.InsumoAutocomplete.as_view(), name="insumo"),
        path("producto/", viewsAutocomplete.ProductoAutocomplete.as_view(), name="producto"),
        path("tipoDeAtencion/", viewsAutocomplete.TipoDeAtencionAutocomplete.as_view(), name="tipoDeAtencion"),
        path("cliente/", viewsAutocomplete.ClienteAutocomplete.as_view(), name="cliente"),
        path("mascota/<int:cliente>/", viewsAutocomplete.MascotaAutocomplete.as_view(), name="mascota"),
        path("mascota/", viewsAutocomplete.MascotaAutocomplete.as_view(), name="mascota"),
        path("practicaRealizada/", viewsAutocomplete.PracticaRealizadaAutocomplete.as_view(), name="practicaRealizada"),
    ], "autocomplete")))
]

VeterinariaPatagonica/Apps/GestionDeFacturas/models.py
from decimal import Decimal
from datetime import datetime

from django.db import models
from django.core.validators import RegexValidator, MinValueValidator

from VeterinariaPatagonica.tools import R
from Apps.GestionDeProductos import models as proModel
from Apps.GestionDeClientes import models as cliModel
from Apps.GestionDePracticas.models.practica import Practica
from Apps.GestionDePagos.models import Pago

REGEXTIPO = '^[A-B-C]{1}$'
MAXTIPO = 1
MAXDECIMAL = 2
MAXDIGITO = 8

MAX_DIGITOS_AJUSTES = 5
MAX_DECIMALES_AJUSTES = 2


class ListadosQuerySet(models.QuerySet):

    MAPEO_ORDEN = {
        "id" : ["id"],
        "tipo" : ["tipo"],
        "total" : ["total"],
        "fecha" : ["fecha"],
        "cliente" : ["cliente__apellidos", "cliente__nombres"],
        "precioPractica" : ["practica__precio"],
        "pago" : ["pago__importeTotal"],
        "fechaPago" : ["pago__fecha"],
        "importeVentas" : ["importe_ventas"],
    }

    MAPEO_FILTRADO = {
        "importe_desde" : "total__gte",
        "importe_hasta" : "total__lte",
        "tipo": "tipo",
        "cliente": lambda value: R(
            cliente__dniCuit__icontains=value,
            cliente__nombres__icontains=value,
            cliente__apellidos__icontains=value
        ),
        "fecha_desde": "fecha__gte",
        "fecha_hasta": "fecha__lte",
        "productos" : lambda values: R(*[
            R(
                productos__nombre__icontains=value,
                productos__descripcion__icontains=value,
                productos__marca__icontains=value
            ) for value in values
        ]),
        "rubros" : lambda values: R(*[
            R(
                productos__rubro__nombre__icontains=value,
                productos__rubro__descripcion__icontains=value
            ) for value in values
        ])
    }


ListadoManager = models.Manager.from_queryset(ListadosQuerySet)


class Factura(models.Model):

    class Meta:
        ordering = ["-fecha", "tipo"]
        permissions=(
            ("factura_crear", "crear"),
            ("factura_ver_pagas", "ver"),
            ("factura_ver_no_pagas", "ver"),
            ("factura_listar_pagas", "listar pagas"),
            ("factura_listar_no_pagas", "listar no pagas"),
            ("factura_exportar_xlsx_pagas", "exportar a formato xlsx pagas"),
            ("factura_exportar_xlsx_no_pagas", "exportar a formato xlsx no pagas"),
        )
        default_permissions = ()
        unique_together = (
            ("id", "practica"),
        )

    MAPPER = {
        "tipo": "tipo__icontains",
        "cliente": lambda value: models.Q(cliente__nombres__icontains=value) | models.Q(cliente__apellidos__icontains=value),
        "fecha": "fecha_icontains"
    }

    TIPODEFACTURA = (('A','A'), ('B','B'), ('C', 'C'))

    objects = ListadoManager()

    tipo = models.CharField(
        choices=TIPODEFACTURA,
        default='B',
        help_text= "Tipo de Factura.",
        max_length=MAXTIPO,
        unique=False,
        null=False,
        blank=False,
        validators=[RegexValidator(regex=REGEXTIPO)],
        error_messages={
            'max_length': "El tipo de factura puede tener a lo sumo {} caracteres".format(MAXTIPO),
            'blank': "El tipo es obligatorio"
        }
    )

    cliente = models.ForeignKey(
        cliModel.Cliente,
        unique=False,
        blank=False,
        null=False,
        on_delete=models.CASCADE,
        error_messages={
            'blank': "El cliente es obligatorio"
        }
    )

    fecha = models.DateField(
        help_text="Fecha de la Factura.",
        unique=False,
        null=False,
        blank=False,
        default=datetime.now,
        error_messages={
            'blank': "La fecha es obligatoria"
        }
    )

    productos = models.ManyToManyField(
        proModel.Producto,
        through='DetalleFactura',
        through_fields=('factura', 'producto'),
    )

    recargo = models.DecimalField(
            blank=False,
            null = False,
            default=Decimal(0),
            max_digits = MAX_DIGITOS_AJUSTES,
            decimal_places = MAX_DECIMALES_AJUSTES,
            error_messages = {},
            validators = []
    )

    descuento = models.DecimalField(
            blank=False,
            null = False,
            default=Decimal(0),
            max_digits = MAX_DIGITOS_AJUSTES,
            decimal_places = MAX_DECIMALES_AJUSTES,
            error_messages = {},
            validators = []
    )

    practica = models.ForeignKey(
        Practica,
        on_delete = models.CASCADE,
        null = True,
        blank = True
    )

    total = models.DecimalField(
            blank=False,
            null = False,
            default=Decimal(0),
            max_digits = Practica.MAX_DIGITOS,
            decimal_places = Practica.MAX_DECIMALES,
            error_messages = {},
            validators = [
                MinValueValidator(0, "El precio de la factura no puede ser negativo"),
            ]
    )

    def importeDescuentoServicio(self):
        descuento = self.cliente.descuentoServicio
        importe = self.practica.precio if self.practica else Decimal(0.0)
        importeDescuento = importe * descuento / Decimal(100.0)
        return -importeDescuento

    def importeDescuentoProducto(self):
        descuento = self.cliente.descuentoProducto
        importe = sum(detalle.subtotal for detalle in self.detalles_producto.all())
        importeDescuento = importe * descuento / Decimal(100.0)
        return -importeDescuento

    def calcularTotal(self, detalles=[], descuento=0, recargo=0, practica=None):
        importe = Decimal(0)
        importeDetalles = Decimal(0)
        importePractica = Decimal(0)

        if(self.cliente):
            descuentoServicio = self.cliente.descuentoServicio
            descuentoProducto = self.cliente.descuentoProducto
        else:
            descuentoServicio = 0
            descuentoProducto = 0


        if practica is not None:
            importePractica = practica.estados.realizacion().total()
            if descuentoServicio > 0:
                importePractica -= importePractica * descuentoServicio / Decimal(100.0)

        for detalle in detalles:
            importeDetalles += detalle.subtotal
        if importeDetalles > 0 and descuentoProducto > 0:
            importeDetalles -= importeDetalles * descuentoProducto / Decimal(100.0)
        importe = importeDetalles + importePractica
        if (descuento != recargo):
            importe += importe * (recargo - descuento) / Decimal(100.0)
        return importe

    def totalAdeudado(self):
        importeAdelanto = 0
        if self.practica is not None:
            if self.practica.adelanto is not None:
                importeAdelanto = min(self.total, self.practica.adelanto.importe)
        return self.total - importeAdelanto

    def importeDescuento(self):
        a = self.recargo - self.descuento
        if a != -100:
            retorno = self.total * self.descuento / Decimal(100+a)
        else:
            practica = self.practica.precio if self.practica else Decimal(0)
            productos = sum( detalle.subtotal for detalle in self.detalles_producto.all() )
            retorno = (practica + productos) * self.descuento / Decimal(100)
        return -retorno

    def importeRecargo(self):
        a = self.recargo - self.descuento
        if a != -100:
            retorno = self.total * self.recargo / Decimal(100+a)
        else:
            practica = self.practica.precio if self.practica else Decimal(0)
            productos = sum( detalle.subtotal for detalle in self.detalles_producto.all() )
            retorno = (practica + productos) * self.recargo / Decimal(100)
        return retorno

    def importeNeto(self):
        return self.total * 100 / Decimal(121)

    def importeIVA(self):
        return self.total - self.importeNeto()

    def estaPaga(self):
        return Pago.objects.filter(factura=self).exists()


    def importeProductosConDescuento(self):
        # importeDetalles = Decimal(0)
        # detalles = self.detalles_producto.all()
        # if(self.cliente):
        #     descuentoProducto = self.cliente.descuentoProducto
        # else:
        #     descuentoProducto = 0
        # for detalle in detalles:
        #     importeDetalles += detalle.subtotal
        # if descuentoProducto>0:
        #     importeDetalles = importeDetalles - ((importeDetalles*descuentoProducto)/100)
        #
        # auxCadena=('%.2f' % importeDetalles).rstrip('0').rstrip('.')
        # valorDevuelto = int(auxCadena)

        # return auxCadena
        return 0

    def __str__(self):
        cadena = 'Tipo de Factura: {0}, Cliente: {1} Total: {2}.'
        return cadena.format(self.tipo, self.cliente, self.total)


class DetalleFactura(models.Model):

    class Meta:
        unique_together = ("factura", "producto")
        index_together = ["factura", "producto"]

    factura = models.ForeignKey(
        Factura,
        on_delete=models.CASCADE,
        help_text="Ingrese numero de Factura",
        unique=False,
        null=False,
        blank=False,
        related_name="detalles_producto",
        error_messages={
            'blank': "La Factura es obligatoria"
        }
    )

    producto = models.ForeignKey(
        proModel.Producto,
        on_delete=models.CASCADE,
        unique=False,
        null=False,
        blank=False,
        related_name="detalles_factura",
        error_messages={
            'blank': "Debe ingresar al menos un producto"
        }
    )

    cantidad = models.PositiveIntegerField()

    subtotal = models.DecimalField(
        null= True,
        max_digits= MAXDIGITO,
        decimal_places= MAXDECIMAL,
    )

    def  __unicode__(self):
        return self.subtotal

    def precioPorUnidad(self):
        return self.subtotal / Decimal(self.cantidad)

    def save(self, *args, **kwargs):

VeterinariaPatagonica/templates/OtraGestionDeFacturas/GestionDeFacturas.html
{% extends "sitioBase.html" %}
{% load static %}
{% block paginaSeccionGeneral %}
    <section>
        <div class="row">
            <div class="col-xs-10 col-sm-11 col-md-11">
              <h4 class="titulo">
                {% block factura-titulo %}
                {% endblock %}
              </h4>
            </div>
            <div class="col-xs-2 col-sm-1 col-md-1">
              <a href="{% url 'facturas:ayudaCostos' %}" target="_blank">
                <i class="glyphicon glyphicon-book"></i>
              </a>
            </div>
        </div>
        {% block factura-contenido %}
        {% endblock %}
    </section>

    
{% endblock %}

VeterinariaPatagonica/templates/OtraGestionDeFacturas/exportar.html
{% extends "./listar.html" %}
{% block titulo %}
Exportar listado de facturas en formato {{ formato }}
{% endblock %}
{% block listado-titulo %}
{% include "snippets/titulo.html" with titulo="Exportar listado de facturas en formato "|add:formato %}
{% endblock %}
{% block submit %}
{% for accion in exportar.acciones %}
<div class="col-xs-6 col-sm-4 col-md-2 form-group pull-right submit">
    {{ accion }}
</div>
{% endfor %}
<div class="col-xs-4 col-sm-3 col-md-2 form-group pull-right submit">
    <button class="btn btn-sm btn-default" value="" type="submit">Actualizar</button>
</div>
{% if gestor.paginar %}
{{ gestor.paginacion.pagina_actual }}
<div class="col-xs-8 col-sm-8 col-md-4 form-group pull-right {{ gestor.paginacion.cantidad.name }} {% if gestor.paginacion.cantidad.errors %}has-error{% endif %}">
    <div class="input-group">
        <div class="input-group-addon"> {{ gestor.paginacion.cantidad.label }} </div>
        {{ gestor.paginacion.cantidad }}
    </div>
</div>
{% endif %}
{% endblock %}

VeterinariaPatagonica/templates/OtraGestionDeFacturas/facturar.html
{% extends 'OtraGestionDeFacturas/GestionDeFacturas.html' %}
{% load static %}
{% block paginaEstilos %}
    {{ formset.media.css }}
    {{ block.super }}
    <link href="{% static "vendor/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css" %}" rel="stylesheet">
{% endblock %}
{% block titulo %}
Facturar
{% endblock %}
{% block factura-titulo %}
{% include "snippets/titulo.html" with titulo="Facturar" %}
{% endblock %}
{% block factura-contenido %}
<div class="contenedor">
    {% include "snippets/errores.html" %}
    {% if accion %}
    {% with factura=form.factura %}
        <form id="form-facturar" class="form-horizontal formulario" action="{{ request.path }}" method="POST" onsubmit="validar(event);">
            {% if factura.total is not None %}
            <div class="cuadro">
                <div class="row cuadro-contenido resumen">
                    {% if factura.cliente and factura.cliente.tipoDeCliente == "E" %}
                    <div class="col-xs-12 col-sm-6 col-md-6 bloque">
                        <div class="dato descuento-servicio">
                            <i class="fa fa-dot-circle-o"></i><b>Descuento en servicios:</b> %<span class="valor">{{ factura.cliente.descuentoServicio|floatformat:2 }}</span>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 bloque">
                        <div class="dato descuento-productos">
                            <i class="fa fa-dot-circle-o"></i><b>Descuento en productos:</b> %<span class="valor">{{ factura.cliente.descuentoProducto|floatformat:2 }}</span>
                        </div>
                    </div>
                    {% endif %}
                    <div class="col-xs-12 col-sm-6 col-md-6 bloque">
                        <div class="dato importe">
                            <i class="fa fa-dot-circle-o"></i><b>Importe:</b> $<span class="valor">{{ factura.total|floatformat:2 }}</span>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 bloque">
                    {% if factura.practica.adelanto %}
                        <div class="dato adelanto">
                            <i class="fa fa-dot-circle-o"></i><b>Adelanto:</b> $<span class="valor">{{ factura.practica.adelanto.importe|floatformat:2 }}</span>
                        </div>
                    {% endif %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% csrf_token %}
            <div id="form-facturar-errores">
                {% if form.errors or formset.total_error_count %}
                    <div class="errores">
                        <b>Por favor revise los siguientes errores:</b>
                        <ul>
                            {% include 'snippets/formErrores.html' %}
                            {% include 'snippets/formsetErrores.html' %}
                        </ul>
                    </div>
                {% endif %}
            </div>
            {% block formularioFactura %}
            {% include "snippets/field.html" with field=form.cliente %}
            {% include "snippets/field.html" with field=form.practica %}
            {% include "snippets/field.html" with field=form.tipo %}
            {% include "snippets/calendarField.html" with field=form.fecha %}
            {% include "snippets/field.html" with field=form.recargo %}
            {% include "snippets/field.html" with field=form.descuento %}
            {% endblock %}
            <div class="form-group productos">
                <div class="row productos">
                    <label for="formset-productos" class="col-xs-12 col-sm-2 col-md-4 control-label etiqueta">
                        Productos
                    </label>
                    <div class="col-xs-12 col-sm-10 col-md-8 control" id="formset-productos">
                        {% include "snippets/ayuda.html" with id="ayuda-servicios" content="Puede agregar a la facturación la venta de productos. Las cantidades deben ser mayores a cero y no pueden haber items duplicados." %}
                        {% include "snippets/formset.html" with titulo="" %}
                    </div>
                </div>
            </div>
            {% include "snippets/form.html" with form=acciones accion=None %}
        </form>
    {% endwith %}
    {% endif %}
</div>
{% endblock %}
{% block paginaJavascript %}
    {{ formset.media.js }}
    {{ block.super }}
    <script src="{% static "vendor/moment/moment.js" %}"></script>
    <script src="{% static "vendor/moment/locale/es.js" %}"></script>
    <script src="{% static "vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js" %}"></script>
    <script type="text/javascript">
        var validadores = [
            {
                "validador" : validarFormset,
                "argumentos" : {
                    "validarCantidades" : false,
                    "comparador" : compararProductos,
                    "formset_id" : "{{ formset.prefix }}-formset",
                    "errores" : document.getElementById("form-facturar-errores"),
                }
            }
        ]
        var productos = document.getElementById('{{ formset.prefix }}-formset');
        actualizarEliminar(productos);
        document.onreadystatechange = function(){
            $("#{{ form.fecha.name|add:"_calendar" }}").datetimepicker({
                locale:"es",
                format: 'L',
            });
        }
    </script>
{% endblock %}

VeterinariaPatagonica/templates/OtraGestionDeFacturas/ver.html
{% extends 'OtraGestionDeFacturas/GestionDeFacturas.html' %}
{% block titulo %}
Ver factura
{% endblock %}
{% block factura-titulo %}
{% with id=factura.id|stringformat:"d" %}
{% include "snippets/titulo.html" with titulo="Factura número "|add:id %}
{% endwith %}
{% endblock %}
{% block factura-contenido %}
<div class="contenedor">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-6">
            <p><b>Factura número:</b> {{ factura.id }}</p>
            <p><b>Factura tipo:</b> {{ factura.get_tipo_display }}</p>
            <p><b>Fecha de facturación:</b> {{ factura.fecha|date:"d/m/y" }}</p>
            {% if not cliente.baja and perms.GestionDeClientes.cliente_ver %}
            <b><a href="{% url "clientes:clienteVer" factura.cliente.id %}">Cliente:</a></b>
            {% else %}
            <b>Cliente:</b>
            {% endif %}
            <ul>
                <li><b>DNI/CUIT:</b> {{ factura.cliente.dniCuit }}</li>
                <li><b>Nombre:</b> {{ factura.cliente.apellidos }} {{ factura.cliente.nombres }} (cliente {{ factura.cliente.get_tipoDeCliente_display|lower }})</li>
                <li><b>Dirección:</b> {{ factura.cliente.direccion }}, {{ factura.cliente.localidad }}</li>
            </ul>
            <p><b>Paga:</b> {{ factura.pago|yesno }}</p>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-6">
            {% if factura.pago and perms.GestionDePagos.pago_ver %}
            <div class="cuadro">
                <div class="cuadro-titulo">Pago</div>
                <div class="cuadro-contenido">
                    <p><b>Identificador:</b> {{ factura.pago.id }}</p>
                    <p><b>Fecha de emisión:</b> {{ factura.pago.fecha|date:"d/m/y" }}</p>
                    <p><b>Importe:</b> ${{ factura.total|floatformat:2 }}</p>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="col-xs-12">
            <b>Detalles:</b>
            <div class="table-responsive">
                <table class="table-bordered detalles" id="factura">
                    <colgroup>
                        <col class="cantidad">
                        <col class="producto">
                        <col class="precio">
                        <col class="importe">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>Cantidad</th>
                            <th>Descripción</th>
                            <th>Precio</th>
                            <th>Importe</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if factura.practica %}
                        {% with descripcion="Servicio de atención clínica ("|add:factura.practica.nombreTipo|add:": "|add:factura.practica.tipoDeAtencion.nombre|add:")" %}
                        <tr>
                            <td>1</td>
                            <td>
                            {% if urlPractica %}
                                <a href="{{ urlPractica }}">{{ descripcion }}</a>
                            {% else %}
                                {{ descripcion }}
                            {% endif %}
                            </td>
                            <td>{{ factura.practica.precio|floatformat:2 }}</td>
                            <td>{{ factura.practica.precio|floatformat:2 }}</td>
                        </tr>
                        {% endwith %}
                        {% if factura.cliente.tipoDeCliente == "E" %}
                        <tr class="breve">
                            <td colspan="3">
                                Descuento en servicios (cliente especial) %{{ factura.cliente.descuentoServicio|floatformat:2 }}
                            </td>
                            <td>{{ factura.importeDescuentoServicio|floatformat:2 }}</td>
                        </tr>
                        {% endif %}
                        {% endif %}
                        {% for detalle in factura.detalles_producto.all %}
                        <tr>
                            <td>{{ detalle.cantidad }}</td>
                            <td>
                            {% if not detalle.producto.baja and perms.GestionDeServicios.producto_ver_habilitados %}
                                <a href="{% url "productos:productoVer" detalle.producto.id %}">
                                    {{ detalle.producto.nombre }}
                                </a>
                            {% else %}
                                {{ detalle.producto.nombre }}
                            {% endif %}
                            </td>
                            <td>{{ detalle.precioPorUnidad|floatformat:2 }}</td>
                            <td>{{ detalle.subtotal|floatformat:2 }}</td>
                        </tr>
                        {% endfor %}

                        {% if factura.cliente.tipoDeCliente == "E" and factura.detalles_producto.count %}
                        <tr class="breve">
                            <td colspan="3">
                                Descuento en productos (cliente especial) %{{ factura.cliente.descuentoProducto|floatformat:2 }}
                            </td>
                            <td>{{ factura.importeDescuentoProducto|floatformat:2 }}</td>
                        </tr>
                        {% endif %}
                        

                        {% if factura.descuento != 0 %}
                        <tr class="breve">
                            <td colspan="3">
                                Descuento del %{{ factura.descuento|floatformat:2 }}
                            </td>
                            <td>{{ factura.importeDescuento|floatformat:2 }}</td>
                        </tr>
                        {% endif %}
                        {% if factura.recargo != 0 %}
                        <tr class="breve">
                            <td colspan="3">
                                Recargo del %{{ factura.recargo|floatformat:2 }}
                            </td>
                            <td>{{ factura.importeRecargo|floatformat:2 }}</td>
                        </tr>
                        {% endif %}
                        {% if factura.tipo == "A" %}
                        <tr class="breve">
                            <td colspan="3">Importe neto</td>
                            <td>{{ factura.importeNeto|floatformat:2 }}</td>
                        </tr>
                        <tr class="breve">
                            <td colspan="3">IVA 21%</td>
                            <td>{{ factura.importeIVA|floatformat:2 }}</td>
                        </tr>
                        {% endif %}
                        <tr class="breve total">
                            <td colspan="3">Total</td>
                            <td>${{ factura.total|floatformat:2 }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}