VeterinariaPatagonica/Apps/GestionDeClientes/urls.py
from django.conf.urls import url
from django.urls import path
from . import views as clientes_views
from VeterinariaPatagonica import views

app_name = 'clientes'

urlpatterns = [

    url(r'^$', clientes_views.clientes, name="cliente"),
    path('crear/', clientes_views.modificar, name="clienteCrear"),
    path('crear/<int:irAMascotas>', clientes_views.modificar, name="clienteCrear"),
    path('modificar/<int:id>/', clientes_views.modificar, name="clienteModificar"),
    path('habilitar/<int:id>/', clientes_views.habilitar, name="clienteHabilitar"),
    path('deshabilitar/<int:id>/', clientes_views.deshabilitar, name="clienteDeshabilitar"),
    path('eliminar/<int:id>/', clientes_views.eliminar, name="clienteEliminar"),
    path('ver/<int:id>/', clientes_views.ver, name="clienteVer"),
    path('verDeshabilitados/', clientes_views.verDeshabilitados, name="clienteVerDeshabilitados"),
    path('verHabilitados/', clientes_views.verHabilitados, name="clienteVerHabilitados"),
    path('listado_clientes_excel/', clientes_views.ListadoClientesExcel, name="clientesListadoEXCEL"),
    path('listado_clientes_pdf/', clientes_views.ListadoClientesPDF, name="clientesListadoPDF"),
    path('ayudaCliente/', clientes_views.ayudaContextualCliente, name="ayudaCliente"),
    path('reporteTipo/', clientes_views.reporteTipo, name='reporteTipo'),
    path('reporte/', clientes_views.reporteTopCliente, name='reporte'),
    path('reportes/', clientes_views.reportes, name='reportes'),
    #path('listado_clientes_excel/', clientes_views.exportar,{"formato" : "xlsx"} , name="clientesListadoEXCEL"),
]

VeterinariaPatagonica/Apps/GestionDeServicios/urls.py
from django.urls import path
from . import views as servicios_views
from VeterinariaPatagonica import views

app_name = 'servicios'
urlpatterns = [
    path('crear/', servicios_views.modificar, name= 'servicioCrear'),
    path('modificar/<int:id>/', servicios_views.modificar, name="servicioModificar"),
    path('ver/<int:id>/', servicios_views.ver, name='servicioVer'),
    path('deshabilitar/<int:id>/', servicios_views.deshabilitar, name='servicioDeshabilitar'),
    path('habilitar/<int:id>/', servicios_views.habilitar, name='servicioHabilitar'),
    path('eliminar/<int:id>/', servicios_views.eliminar, name='servicioEliminar'),

    # path('verHabilitados/', servicios_views.verHabilitados, name='servicioVerHabilitados'),
    # path('verDeshabilitados/', servicios_views.verDeshabilitados, name='servicioVerDeshabilitados'),
    path('verHabilitados/', servicios_views.listar, {"habilitados":True}, name='servicioVerHabilitados'),
    path('verDeshabilitados/', servicios_views.listar, {"habilitados":False}, name='servicioVerDeshabilitados'),
    path('ayudaServicio/', servicios_views.ayudaContextualServicio, name='ayudaServicio'),
    path('listado_servicios_excel/', servicios_views.ListadoServiciosExcel, name="serviciosListadoEXCEL"),
    path('listado_servicios_pdf/', servicios_views.ListadoServiciosPDF, name="serviciosListadoPDF"),
    #path('volver/',servicios_views.volver, name='volver'),
]

VeterinariaPatagonica/VeterinariaPatagonica/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from . import views, viewsAutocomplete

app_name ="bases"
urlpatterns = [
    path("", views.index, name='index'),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("admin/", admin.site.urls),
    path('password/',include ('Apps.Usuarios.urls',namespace='usuarios')),
    path('ayuda/', views.ayuda, name='ayuda'),
    path("GestionDeClientes/", include("Apps.GestionDeClientes.urls", namespace= "clientes")),
    path("GestionDeMascotas/", include("Apps.GestionDeMascotas.urls", namespace= "mascotas")),
    path("GestionDeProductos/",include("Apps.GestionDeProductos.urls", namespace="productos")),
    path("GestionDeRubros/", include("Apps.GestionDeRubros.urls", namespace= "rubros")),
    path("GestionDeServicios/", include("Apps.GestionDeServicios.urls", namespace= "servicios")),
    path("GestionDeTiposDeAtencion/",include("Apps.GestionDeTiposDeAtencion.urls", namespace= "tiposdeatencion")),
    path("GestionDePagos/",include("Apps.GestionDePagos.urls", namespace="pagos")),
    path("GestionDeFormasDePagos/", include("Apps.GestionDeFormasDePagos.urls", namespace="formasDePagos")),
    path("GestionDeFacturas/", include("Apps.GestionDeFacturas.urls", namespace="facturas")),
    path("GestionDePracticas/", include("Apps.GestionDePracticas.urls", namespace="practicas")),

    path("autocomplete/", include(([
        path("servicio/<str:area>/", viewsAutocomplete.ServicioAutocomplete.as_view(), name="servicio"),
        path("servicio/", viewsAutocomplete.ServicioAutocomplete.as_view(), name="servicio"),
        path("insumo/", viewsAutocomplete.InsumoAutocomplete.as_view(), name="insumo"),
        path("producto/", viewsAutocomplete.ProductoAutocomplete.as_view(), name="producto"),
        path("tipoDeAtencion/", viewsAutocomplete.TipoDeAtencionAutocomplete.as_view(), name="tipoDeAtencion"),
        path("cliente/", viewsAutocomplete.ClienteAutocomplete.as_view(), name="cliente"),
        path("mascota/<int:cliente>/", viewsAutocomplete.MascotaAutocomplete.as_view(), name="mascota"),
        path("mascota/", viewsAutocomplete.MascotaAutocomplete.as_view(), name="mascota"),
        path("practicaRealizada/", viewsAutocomplete.PracticaRealizadaAutocomplete.as_view(), name="practicaRealizada"),
    ], "autocomplete")))
]

VeterinariaPatagonica/VeterinariaPatagonica/Apps/GestionDeServicios/models.py
from django.db import models
from VeterinariaPatagonica.Apps.GestionDeInsumos.models import Insumo
from django.views.generic.list import ListView

# Create your models here.
#class CantidadList(ListView):
#   cantidadInsumos = models.PositiveSmallIntegerField()


class InsumosList(ListView):
    insumo = models.ForeignKey(Insumo, null=False, blank=False, on_delete=models.CASCADE)
    cantidadInsumo = models.PositiveSmallIntegerField

class Servicio(models.Model):
    t_tipo = (('C','Consulta'),('Q','Quirurgica'))
    tipo = models.CharField(max_length=25, choices=t_tipo, default='Tipo de Práctica aqui')
    nombre = models.CharField(max_length=50, null=False, blank=False, help_text='Ingresa el nombre del Servicio')
    descripcion = models.CharField(max_length=200)
    insumos = InsumosList
    #cantidadInsumos = CantidadList
    tiempoEstimado = models.TimeField(auto_now=False, help_text='Tiempo de Duración del Servicio')
    precioManoDeObra = models.PositiveSmallIntegerField()


    def __str__(self):
        cadena = 'Nombre de Servicio: {0}, Duración Estimada: {1} Precio: {2}.'
        return cadena.format(self.nombre, self.tiempoEstimado, self.precioManoDeObra)

VeterinariaPatagonica/Apps/GestionDeServicios/views.py
from django.shortcuts import render
from django.template import loader
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required, permission_required
from django.forms import modelformset_factory

from .models import Servicio, ServicioProducto
from .forms import ServicioForm, ServicioProductoForm, ServicioProductoBaseFormSet
from VeterinariaPatagonica import tools

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse

#Vista genérica para mostrar resultados
from django.views.generic.base import TemplateView
#Workbook nos permite crear libros en excel
from openpyxl import Workbook
from openpyxl.utils import get_column_letter

#Importamos settings para poder tener a la mano la ruta de la carpeta media
from django.conf import settings
from io import BytesIO
from reportlab.pdfgen import canvas
from django.views.generic import View
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from reportlab.lib.units import cm
from reportlab.lib import colors


serviciosFiltrados = []

def menuVer(usuario, servicio):

    menu = [[],[],[],[]]

    if usuario.has_perm("GestionDeServicios.servicio_modificar"):
        menu[0].append( (reverse("servicios:servicioModificar", args=(servicio.id,)), "Modificar servicio") )
        if servicio.baja:
            menu[0].append( (reverse("servicios:servicioHabilitar", args=(servicio.id,)), "Habilitar servicio") )
        else:
            menu[0].append( (reverse("servicios:servicioDeshabilitar", args=(servicio.id,)), "Deshabilitar servicio") )

    if usuario.has_perm("GestionDeServicios.servicio_listar_habilitados"):
        menu[1].append( (reverse("servicios:servicioVerHabilitados"), "Listar servicios habilitados") )
    if usuario.has_perm("GestionDeServicios.servicio_listar_no_habilitados"):
        menu[1].append( (reverse("servicios:servicioVerDeshabilitados"), "Listar servicios deshabilitados") )

    if usuario.has_perm("GestionDeServicios.servicio_crear"):
        menu[2].append( (reverse("servicios:servicioCrear"), "Crear servicio") )

    return [ item for item in menu if len(item) ]

def menuListar(usuario, habilitados):
    menu = [[],[],[],[],[]]

    if (not habilitados) and usuario.has_perm("GestionDeServicios.cliente_ver_habilitados") \
        and usuario.has_perm("GestionDeServicios.cliente_exportar_excel_habilitados"):

        menu[0].append( (reverse("servicios:servicioVerHabilitados"), "Listar servicios habilitados") )
        menu[1].append( (reverse("servicios:serviciosListadoEXCEL"), "Exportar servicios deshabilitados"))
        menu[2].append( (reverse("servicios:serviciosListadoPDF"), "Imprimir servicios deshabilitados"))

    if habilitados and usuario.has_perm("GestionDeServicios.cliente_ver_no_habilitados") \
        and usuario.has_perm("GestionDeServicios.cliente_exportar_excel_deshabilitados"):

        menu[0].append( (reverse("servicios:servicioVerDeshabilitados"), "Listar servicios deshabilitados") )
        menu[1].append( (reverse("servicios:serviciosListadoEXCEL"), "Exportar servicios habilitados") )
        menu[2].append( (reverse("servicios:serviciosListadoPDF"), "Imprimir servicios habilitados") )

    if usuario.has_perm("GestionDeServicios.servicio_crear"):

        menu[3].append( (reverse("servicios:servicioCrear"), "Crear Servicio") )

    return [ item for item in menu if len(item) ]

def menuModificar(usuario, servicio):

    menu = [[],[],[],[],[]]
    if (servicio):
        menu[0].append( (reverse("servicios:servicioVer", args=(servicio.id,)), "Ver servicio") )

        if servicio.baja:
            menu[1].append( (reverse("servicios:servicioHabilitar", args=(servicio.id,)), "Habilitar servicio") )
        else:
            menu[1].append( (reverse("servicios:servicioDeshabilitar", args=(servicio.id,)), "Deshabilitar servicio") )

    if usuario.has_perm("GestionDeServicios.servicio_listar_habilitados"):
        menu[2].append( (reverse("servicios:servicioVerHabilitados"), "Listar servicios habilitados") )
    if usuario.has_perm("GestionDeServicios.servicio_listar_no_habilitados"):
        menu[2].append( (reverse("servicios:servicioVerDeshabilitados"), "Listar servicios deshabilitados") )

    if usuario.has_perm("GestionDeServicios.servicio_crear"):
        menu[3].append( (reverse("servicios:servicioCrear"), "Crear servicio") )

    return [ item for item in menu if len(item) ]

def menuCrear(usuario, servicio):

    menu = [[],[],[],[]]

    if usuario.has_perm("GestionDeServicios.servicio_listar_habilitados"):
        menu[0].append( (reverse("servicios:servicioVerHabilitados"), "Listar servicios habilitados") )
    if usuario.has_perm("GestionDeServicios.servicio_listar_no_habilitados"):
        menu[0].append( (reverse("servicios:servicioVerDeshabilitados"), "Listar servicios deshabilitados") )

    return [ item for item in menu if len(item) ]


@login_required(redirect_field_name='proxima')
@permission_required('GestionDeServicios.add_Servicio', raise_exception=True)
def modificar(request, id = None):
    servicio = Servicio.objects.get(id=id) if id is not None else None
    if (id==None):
        context = {"titulo": 1, 'usuario': request.user}
    else:
        context = {"titulo": 2, 'usuario': request.user}
    form = ServicioForm(instance=servicio)
    ServicioProductoFormset = modelformset_factory(ServicioProducto,#          Defino la forma del formset. Van a tener el checkbox eliminar, la cantidad mínima de forms en el formset
        fields=("producto", "cantidad"), min_num=1, extra=0, can_delete=True,# es de 1 y la máxima es la determinada por django (1000),
        formset=ServicioProductoBaseFormSet)#                                  además se define que siempre va a haber cero tuplas adicionales (extra).
    if request.method == 'POST':
        form = ServicioForm(request.POST, instance=servicio)
        formset = ServicioProductoFormset(request.POST)
        if form.is_valid() and formset.is_valid():#Verifico si los forms del formset cumplen las restricciones definidas (Si no se lanzó un ValidationError).
            servicio = form.save()
            instances = formset.save(commit=False)
            for obj in formset.deleted_objects:#Bucle for que elimina los form que tienen tildado el checkbox "eliminar"
                obj.delete()
            for sproducto in instances:
                sproducto.servicio = servicio
                sproducto.save()

            return HttpResponseRedirect("/GestionDeServicios/ver/{}".format(servicio.id))
        context['form'] = form
        context["formset"] = formset
        context['menu'] = menuModificar(request.user, servicio)
    else:
        context['form'] = form
        qs = ServicioProducto.objects.none() if servicio is None else servicio.servicio_productos.all()#Obtengo los productos ya cargados en el servicio, para poder mostrarlos en el formset.
        context["formset"] = ServicioProductoFormset(queryset=qs)
        context['menu'] = menuCrear(request.user, servicio)
    template = loader.get_template('GestionDeServicios/formulario.html')
    return HttpResponse(template.render(context, request))


# def verHabilitados(request):
#     serviciosQuery = Servicio.objects.habilitados()
#     serviciosQuery = serviciosQuery.filter(tools.paramsToFilter(request.GET, Servicio))
#     template = loader.get_template('GestionDeServicios/verHabilitados.html')

#     paginator = Paginator(serviciosQuery, 1)
#     page = request.GET.get('page')

#     try:
#         servicios = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer, deliver first page.
#         servicios = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range (e.g. 9999), deliver last page of results.
#         servicios = paginator.page(paginator.num_pages)

#     context = {
#         'serviciosQuery' : serviciosQuery,
#         'usuario' : request.user,
#         'servicios': servicios,
#     }

#     return  HttpResponse(template.render(context,request))

# def verDeshabilitados(request):
#     serviciosQuery = Servicio.objects.deshabilitados()
#     serviciosQuery = serviciosQuery.filter(tools.paramsToFilter(request.GET, Servicio))
#     template = loader.get_template('GestionDeServicios/verDeshabilitados.html')

#     paginator = Paginator(serviciosQuery, 1)
#     page = request.GET.get('page')

#     try:
#         servicios = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer, deliver first page.
#         servicios = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range (e.g. 9999), deliver last page of results.
#         servicios = paginator.page(paginator.num_pages)

#     context = {
#         'serviciosQuery': serviciosQuery,
#         'usuario': request.user,
#         'servicios': servicios,
#     }

#     return  HttpResponse(template.render(context,request))

def ver(request, id):
    #import ipdb; ipdb.set_trace()
    try:
        servicio = Servicio.objects.get(id=id)
    except ObjectDoesNotExist:
        raise Http404( "No encontrado", "El servicio con id={} no existe.".format(id) )
    template = loader.get_template('GestionDeServicios/ver.html')
    context = {
        'servicio' : servicio,
        'usuario' : request.user,
        'menu': menuVer(request.user, servicio)
    }
    return HttpResponse(template.render( context, request ))

@login_required(redirect_field_name='proxima')
@permission_required('GestionDeServicios.delete_Servicio', raise_exception=True)
def deshabilitar(request, id):

    try:
        servicio = Servicio.objects.get(id=id)
    except ObjectDoesNotExist:
        raise Http404()

    servicio.baja = True
    servicio.save()

    return HttpResponseRedirect( "/GestionDeServicios/verDeshabilitados/")

VeterinariaPatagonica/Apps/GestionDeServicios/templates/GestionDeServicios/snippets/acciones.html
<div class="menu-colapsable" >
    <div class="item-colapsable" >
        <a role="button" href="#cliente-acciones" data-toggle="collapse">
            <i class="glyphicon glyphicon-tasks"></i>
            <span>Acciones</span>
        </a>
        <div class="contenido-colapsable collapse in" id="cliente-acciones">
            <ul class="acciones sinestilo">

                {% if seccion != 'ver' %}
                    <li><a  class="btn btn-sm btn-default" href="{% url 'clientes:clienteVer'  item.id %}">Ver detalles</a></li>
                {% endif %}

                {% if seccion != 'modificar' %}
                    <li><a  class="btn btn-sm btn-default" href="{% url 'clientes:clienteModificar' item.id %}">Modificar</a></li>
                {% endif %}

                {% if item.baja == False %}
                    <li><a  class="btn btn-sm btn-default" href="{% url 'clientes:clienteDeshabilitar' item.id %}">Deshabilitar</a></li>
                {% else %}
                    <li><a  class="btn btn-sm btn-default" href="{% url 'clientes:clienteHabilitar' item.id %}">Habilitar</a></li>
                    <li><a  class="btn btn-sm btn-default" href="{% url 'clientes:clienteEliminar' item.id %}">Eliminar</a></li>
                {% endif %}


            </ul>
        </div>
    </div>
</div>

VeterinariaPatagonica/Apps/GestionDeServicios/templates/GestionDeServicios/snippets/form.html
<div class="form-group {{ form.tipo.name }} {% if form.tipo.errors %}has-error{% endif %}">
    {% include "snippets/field.html" with field=form.tipo %}
</div>
<div class="form-group {{ form.nombre.name }} {% if form.nombre.errors %}has-error{% endif %}">
    {% include "snippets/field.html" with field=form.nombre %}
</div>
<div class="form-group {{ form.descripcion.name }} {% if form.descripcion.errors %}has-error{% endif %}">
    {% include "snippets/field.html" with field=form.descripcion %}
</div>
<div class="form-group {{ form.tiempoEstimado.name }} {% if form.tiempoEstimado.errors %}has-error{% endif %}">
    {% include "snippets/field.html" with field=form.tiempoEstimado %}
</div>
<div class="form-group {{ form.precioManoDeObra.name }} {% if form.precioManoDeObra.errors %}has-error{% endif %}">
    {% include "snippets/field.html" with field=form.precioManoDeObra %}
</div>
<div class="form-group {{ form.productos.name }} {% if form.productos.errors %}has-error{% endif %}">
    {% include "snippets/field.html" with field=form.productos %}
</div>
{% if accion %}
<div class="form-group">
    <div class=row>
        <div class="col-sm-offset-4 col-sm-8">
            <button type="submit" name="submit-accion" value="{{ accion }}" class="btn btn-sm btn-default">{{ accion|capfirst }}</button>
        </div>
     </div>
</div>
{% endif %}

VeterinariaPatagonica/Apps/GestionDeServicios/templates/GestionDeServicios/snippets/listado.html
<form class="form-inline listado" action="{{ request.get_full_path }}" method="GET">

    <div class="hidden orden-listado">
        {% for field in gestor.formOrden %}
            {{ field }}
        {% endfor %}
        {{ gestor.formPagina.desde }}
    </div>

    <div class="sombreado" id="filtrar-clientes">
        {{ gestor.formFiltros.dniCuit }}
        {{ gestor.formFiltros.apellidos }}
        {{ gestor.formFiltros.nombres }}
        {{ gestor.formFiltros.localidad }}
        {{ gestor.formFiltros.tipoDeCliente }}
        {{ gestor.formPagina.resultados }}
        <button class="btn btn-default filtrar" type="submit">Filtrar</button>
    </div>

    {% if gestor.numero_items %}
        <table class="table table-bordered table-responsive items">
            <colgroup>
                <col class="columna{% if gestor.encabezado.orden_dniCuit.activa %} activa{% endif %}"/>
                <col class="columna{% if gestor.encabezado.orden_apellidos.activa %} activa{% endif %}"/>
                <col class="columna{% if gestor.encabezado.orden_nombres.activa %} activa{% endif %}"/>
                <col class="columna{% if gestor.encabezado.orden_localidad.activa %} activa{% endif %}"/>
                <col class="columna{% if gestor.encabezado.orden_tipoDeCliente.activa %} activa{% endif %}"/>
            </colgroup>
            <thead>
                <tr>
                    <th>{% include "snippets/encabezado.html" with columna=gestor.encabezado.orden_dniCuit %}</th>
                    <th>{% include "snippets/encabezado.html" with columna=gestor.encabezado.orden_apellidos %}</th>
                    <th>{% include "snippets/encabezado.html" with columna=gestor.encabezado.orden_nombres %}</th>
                    <th>{% include "snippets/encabezado.html" with columna=gestor.encabezado.orden_localidad %}</th>
                    <th>{% include "snippets/encabezado.html" with columna=gestor.encabezado.orden_tipoDeCliente %}</th>
                </tr>
            </thead>
            <tbody>
                {% for cliente in gestor.items_actuales %}
                    <tr>
                        <td>
                            <a href="{% url 'clientes:clienteVer' cliente.id %}">
                                {{ cliente.dniCuit }}</a>
                        </td>
                            <td> <p>{{cliente.apellidos}}</p></td>
                            <td> <p>{{cliente.nombres }}</p></td>
                            <td> <p>{{cliente.localidad }}</p></td>
                            <td> <p>{{cliente.tipoDeCliente }}</p></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <div>
        {% include "snippets/paginacion.html" with links=gestor.paginas%}
        </div>
    </form>
    {% else %}

        <p><strong>No hay clientes que mostrar</strong></p>

    {% endif %}

VeterinariaPatagonica/Apps/GestionDeServicios/templates/GestionDeServicios/snippets/secciones.html
<div class="secciones">

    
      
    <a id="clienteAyuda" class="btn btn-sm btn-default" target="_blank" href=""  data-toggle="tooltip" data-placement="bottom" title="Ayuda"> <i class="glyphicon glyphicon-book"> </i></a>

    <a id="link-habilitados" class="btn btn-sm btn-default {% if pagina == 'verHabilitados' %} disabled {% endif %}"  href="{% url 'clientes:clienteVerHabilitados' %}"> Habilitados </a>

    <a id="link-deshabilitados" class="btn btn-sm btn-default {% if pagina == 'verDeshabilitados' %} disabled {% endif %}"  href="{% url 'clientes:clienteVerDeshabilitados' %}"> Deshabilitados </a>

</div>